// src/components/layouts/main.tsx
'use client';

import { content } from '@/contexts/scroll_ref';
import H1 from '@/components/typography/h1';
import { usePathname } from 'next/navigation';
import NextTools from '@/classes/next_tools';

export default function Main({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();
  return (
    <>
      <div className={'bg-granny-smith-apple dark:bg-indigo-dye rounded-lg flex flex-1 items-center justify-center'}>
        <H1 className={'font-bold first-letter:uppercase'}>{NextTools.pageName({ pathname })}</H1>
      </div>
      <div
        className={'bg-granny-smith-apple dark:bg-indigo-dye rounded-lg flex flex-[9_9_0%] overflow-y-auto'}
        ref={content}
      >
        {children}
      </div>
    </>
  );
}

// src/components/layouts/main.vue
<script lang="ts" setup>
import NuxtTools from '@/classes/nuxt_tools';
import { content as globalContent } from '@/contexts/scroll_ref';

const content = ref<HTMLDivElement>();

onMounted(() => {
  globalContent.value = content.value;
});
</script>
<template>
  <div class="flex h-full w-full flex-col space-y-2">
    <div
      class="flex flex-1 items-center justify-center rounded-lg bg-granny-smith-apple dark:bg-indigo-dye"
    >
      <FontsH1 class="font-bold first-letter:uppercase">
        {{ NuxtTools.pageName({ pathname: $route.path }) }}
      </FontsH1>
    </div>
    <div
      ref="content"
      class="flex flex-[9_9_0%] overflow-y-auto rounded-lg bg-granny-smith-apple dark:bg-indigo-dye"
    >
      <slot />
    </div>
  </div>
</template>
