// src/pages/projects.vue
<script lang="ts" setup>
import { ArrowTrendingUpIcon, EyeIcon, StarIcon } from '@heroicons/vue/24/solid';
import { content } from '@/contexts/scroll_ref';
import { IRepo } from '@/types/repos';

const repos = useState<IRepo[]>('repos');
const reposPage = useState<number>('reposPage');

function getStatusText({ isArchived, isPrivate }: { isArchived: IRepo['archived']; isPrivate: IRepo['private'] }) {
  if (!isArchived) return isPrivate ? 'Private' : 'Public';
  return isArchived && !isPrivate ? 'Public Archive' : 'Private Archive';
}

function getStatusClass({ isArchived, isPrivate }: { isArchived: IRepo['archived']; isPrivate: IRepo['private'] }) {
  if (!isArchived) return isPrivate ? 'bg-red-500' : 'bg-green-500';
  return isArchived && !isPrivate ? 'bg-yellow-500' : 'bg-orange-500';
}

async function getReposPage() {
  const newRepos = await getRepos({ page: reposPage.value });
  repos.value = [...repos.value, ...newRepos];
}

async function handleScroll() {
  if (content?.value) {
    const scrollPosition = content.value.scrollHeight - content.value.clientHeight;
    if (Math.ceil(content.value.scrollTop) >= scrollPosition) {
      reposPage.value++;
      await getReposPage();
    }
  }
}

onMounted(async () => {
  if (!repos.value.length) await getReposPage();
  if (content?.value) {
    content.value.addEventListener('scroll', handleScroll);
  }
});

onBeforeUnmount(() => {
  if (content?.value) {
    content.value.removeEventListener('scroll', handleScroll);
  }
});
</script>
<template>
  <div class="h-fit w-fit m-2">
    <NuxtLink
      v-for="(repo, i) in repos"
      :key="repo.id"
      :href="repo.html_url"
      target="_blank"
      rel="noopener noreferrer"
      :class="`${repo.private ? 'cursor-not-allowed' : 'cursor-pointer'}`"
    >
      <div
        :class="`bg-medium-spring-green dark:bg-prussian-blue shadow-md rounded-lg p-4 hover:shadow-lg transition-shadow ${
          i !== repos.length - 1 ? 'mb-2' : ''
        } ${i !== 0 ? 'mt-2' : ''}`"
      >
        <div class="flex gap-2 items-center mb-2">
          <span
            :class="`inline-block rounded px-2 py-1 text-sm text-white ${getStatusClass({
              isArchived: repo.archived,
              isPrivate: repo.private,
            })}`"
          >
            {{ getStatusText({ isArchived: repo.archived, isPrivate: repo.private }) }}
          </span>
          <FontsH2 class="font-medium break-all">
            {{ repo.owner.login }}/{{ repo.name }}
          </FontsH2>
        </div>
        <p class="mt-1">
          {{ repo.description }}
        </p>
        <div class="flex flex-wrap gap-2 items-center mt-2">
          <span
            v-if="repo.language"
            title="Language"
            :class="`bg-keppel dark:bg-cadet-blue rounded-full px-3 py-1 text-sm`"
          >
            <p>{{ repo.language }}</p>
          </span>
          <span
            title="Stars"
            :class="`flex flex-row space-x-2 bg-keppel dark:bg-cadet-blue rounded-full px-3 py-1 text-sm`"
          >
            <StarIcon class="w-5 h-5" />
            <p>{{ repo.stargazers_count }}</p>
          </span>
          <span
            title="Watchers"
            :class="`flex flex-row space-x-2 bg-keppel dark:bg-cadet-blue rounded-full px-3 py-1 text-sm`"
          >
            <EyeIcon class="w-5 h-5" />
            <p>{{ repo.watchers_count }}</p>
          </span>
          <span
            title="Forks"
            :class="`flex flex-row space-x-2 bg-keppel dark:bg-cadet-blue rounded-full px-3 py-1 text-sm`"
          >
            <ArrowTrendingUpIcon class="w-5 h-5" />
            <p>{{ repo.forks_count }}</p>
          </span>
        </div>
      </div>
    </NuxtLink>
  </div>
</template>

// src/pages/projects.tsx
import NextTools from '@/classes/next_tools';
import { content } from '@/contexts/scroll_ref';
import { INextPageWithLayout } from '@/types/app';
import { IRepo } from '@/types/repos';
import { useEffect, useState } from 'react';
import { useFetchRepos } from '@/hooks/useFetchRepos';

const ProjectsPage: INextPageWithLayout = ({ className }) => {
  const [page, setPage] = useState<number>(1);
  const { repos, isLoading } = useFetchRepos({ page });

  useEffect(() => {
    const handleScroll = () => {
      if (content?.current) {
        const scrollPosition = content.current.scrollHeight - content.current.clientHeight;
        if (Math.ceil(content.current.scrollTop) >= scrollPosition) {
          if (!isLoading) setPage((currentPage) => currentPage + 1);
        }
      }
    };
    if (content?.current) {
      content.current.addEventListener('scroll', handleScroll);
      return () => {
        if (content?.current) content.current.removeEventListener('scroll', handleScroll);
      };
    }
  }, [isLoading]);

  const isPrivate = ({ privacy }: { privacy: IRepo['private'] }) => {
    return (
      <span className={`inline-block rounded px-2 py-1 text-sm text-white ${privacy ? 'bg-red-500' : 'bg-green-500'}`}>
        {privacy ? 'Private' : 'Public'}
      </span>
    );
  };

  const status = ({ archived, privacy }: { archived: IRepo['archived']; privacy: IRepo['private'] }) => {
    if (!archived) return isPrivate({ privacy });
    return (
      <span
        className={`inline-block rounded px-2 py-1 text-sm  text-white ${
          archived && !privacy ? 'bg-yellow-500' : 'bg-orange-500'
        }`}
      >
        {archived && !privacy ? 'Public Archive' : 'Private Archive'}
      </span>
    );
  };

  return (
    <div className={[className, 'h-fit w-full'].filter(Boolean).join(' ')}>
      {repos?.map((repo, i, repos) => (
        <a key={repo.id} href={repo.html_url} className={`${repo.private ? 'cursor-not-allowed' : 'cursor-pointer'}`}>
          <div
            className={`bg-medium-spring-green dark:bg-prussian-blue shadow-md rounded-md p-4 hover:shadow-lg transition-shadow ${
              i !== repos.length - 1 ? 'mb-2' : ''
            } ${i !== 0 ? 'mt-2' : ''}`}
          >
            <div className={'flex items-center mb-2'}>
              {status({ privacy: repo.private, archived: repo.archived })}
              <h3 className={'text-gunmetal dark:text-tea-green text-lg font-medium ml-2'}>
                {repo.owner.login}/{repo.name}
              </h3>
            </div>
            <p className={'mt-1'}>{repo.description}</p>
            <div className={'flex items-center mt-2'}>
              {repo.language && (
                <span className={'inline-block bg-keppel dark:bg-cadet-blue rounded-full px-3 py-1 text-sm mr-2'}>
                  {repo.language}
                </span>
              )}
              <span className={'inline-block bg-keppel dark:bg-cadet-blue rounded-full px-3 py-1 text-sm mr-2'}>
                {repo.stargazers_count} stars
              </span>
              <span className={'inline-block bg-keppel dark:bg-cadet-blue rounded-full px-3 py-1 text-sm mr-2'}>
                {repo.watchers_count} watchers
              </span>
              <span className={'inline-block bg-keppel dark:bg-cadet-blue rounded-full px-3 py-1 text-sm mr-2'}>
                {repo.forks_count} forks
              </span>
            </div>
          </div>
        </a>
      ))}
    </div>
  );
};

ProjectsPage.getLayout = NextTools.layout.default;

export default ProjectsPage;
