// src/layouts/default.vue
<script lang="ts" setup>
import { IUser } from '@/types/user';

const props = defineProps<{
  user?: IUser;
}>();
</script>
<template>
  <div>
    <div class="flex h-screen w-screen flex-col">
      <header class="sticky w-full">
        <LayoutsHeader :user="props.user" />
      </header>
      <main class="m-4 flex flex-1 flex-col overflow-y-hidden">
        <LayoutsMain>
          <slot />
        </LayoutsMain>
      </main>
      <footer class="sticky w-full">
        <LayoutsFooter :user="props.user" />
      </footer>
    </div>
  </div>
</template>

// src/layouts/default.tsx
import Footer from '@/components/layouts/footer';
import Header from '@/components/layouts/header';
import Main from '@/components/layouts/main';
import { ILayout } from '@/types/layout';
import { getUser } from '@/utils/getUser';

export default async function DefaultLayout({ children }: ILayout) {
  const user = await getUser();

  return (
    <div className={'flex flex-col h-screen w-screen'}>
      <header className={'sticky w-full'}>
        <Header user={user} />
      </header>
      <main className={'flex flex-col flex-1 m-4 space-y-2 overflow-y-hidden'}>
        <Main>{children}</Main>
      </main>
      <footer className={'sticky w-full'}>
        <Footer user={user} />
      </footer>
    </div>
  );
}
